#* PROJECT 		: IAD ASSIGNMENT 1 - Net Benchmark

#* PROGRAMMERS		: Greg Ward

#* FIRST VERSION	: 2016/01/13

#* DESCRIPTION 		: This makefile will create the .exe for the nettest program



EXE := NetTest

SRC := src/*.c
HEADERS:= headers/*.h

CFLAGS := -o

CC := gcc

LDFLAGS := -std=c99 
CLEAN := rm           


########################################


#will make entire program


all: $(EXE)


$(CC) $(LDFLAGS) $(SRC) $(HEADERS) $(CFLAGS) $(EXE)
